#!/bin/bash
#
# This file is part of montime
# https://github.com/seanmctigi/montime
#
# montime is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# montime is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with montime.  If not, see <http://www.gnu.org/licenses/>.

# if we are launching from cron, we need to tell it which display to use
export DISPLAY=:0.0 

PROFILE=~/.montime
LOGFILE=montime.log 

if [ ! -d "$PROFILE" ]; then
  mkdir -p "$PROFILE"
  touch "$PROFILE/$LOGFILE"
fi

function sedeasy {
  sed -i "s/$(echo $1 | sed -e 's/\([[\/.*]\|\]\)/\\&/g')/$(echo $2 | sed -e 's/[\/&]/\\&/g')/g" $3
}

while true; do
  if [[ $(gnome-screensaver-command -q | head -1) =~ "inactive" ]]
  then
    windowid=`xdotool getwindowfocus`
    if [ "$windowid" == "" ]; then
      windowclass='"unknown", "unknown"'
      windowtitle='"unknown"'
    else
      windowclass=`xprop -id $windowid | grep WM_CLASS | sed -e 's/WM_CLASS(STRING) = //'`
      if [ "$windowclass" == "" ]; then
        windowclass='"unknown", "unknown"'
      fi
      windowtitle=`xprop -id $windowid | grep "WM_NAME(STRING)" | sed -e 's/WM_NAME(STRING) = //'`
      if [ "$windowtitle" == "" ]; then
        windowtitle='"unknown"'
      fi
    fi
    data="`date +%Y-%m-%d`, $windowclass, $windowtitle"
  else
    data=`date +%Y-%m-%d`', "inactive", "inactive", "inactive"'
  fi

  pos=`grep "$data" "$PROFILE/$LOGFILE" | wc -l`
  if [ $pos -eq 0 ]; then
    newdata="$data, 1"
    echo "$newdata" >> "$PROFILE/$LOGFILE"
  else
    olddata=`grep "$data" $PROFILE/$LOGFILE`
    newdata=`echo $olddata | awk '{$NF=$NF+1; print $0}'`
    sedeasy "$olddata" "$newdata" "$PROFILE/$LOGFILE"
  fi
  echo $newdata

  sleep 1
done
